In [40]:
import torch
import torch.nn as nn
from torch.optim import SGD
import numpy as np
import matplotlib.pyplot as plt

In [41]:
#defining independent and dependent variables

#independent variable
x = torch.tensor([[6,2],[5,2],[1,3],[7,6]]).float()

#dependent variable
y = torch.tensor([1,5,2,5]).float()

In [42]:
x

tensor([[6., 2.],
        [5., 2.],
        [1., 3.],
        [7., 6.]])

In [43]:
y

tensor([1., 5., 2., 5.])

In [44]:
#creating our first matrix that accepts 2d vector and convert it into 8D vector

M1 = nn.Linear(2,8,bias=False)
M1

Linear(in_features=2, out_features=8, bias=False)

In [45]:
M1(x)

tensor([[-0.8441,  0.9971, -2.8122,  0.0725,  2.7069,  1.5585,  2.0034, -1.3700],
        [-0.8611,  0.9498, -2.3104,  0.2831,  2.2139,  1.5321,  1.6255, -1.1492],
        [-1.4020,  1.1172, -0.2038,  1.7937,  0.1166,  2.1259, -0.0184, -0.2886],
        [-2.7191,  2.4709, -2.9167,  2.5342,  2.6980,  4.3842,  1.8529, -1.6811]],
       grad_fn=<MmBackward0>)

In [46]:
#creating our second matrix that accepts 8D vector and convert it into 1D vector

M2 = nn.Linear(8,1,bias=False)
M2

Linear(in_features=8, out_features=1, bias=False)

In [47]:
M2(M1(x))

tensor([[-1.5966],
        [-1.2879],
        [ 0.0745],
        [-1.3943]], grad_fn=<MmBackward0>)

In [48]:
 M2(M1(x)).squeeze()

tensor([-1.5966, -1.2879,  0.0745, -1.3943], grad_fn=<SqueezeBackward0>)

In [49]:
y

tensor([1., 5., 2., 5.])

In [53]:
#constructing a network using cubclass of nn.Module
class MyNeuralNet(nn.Module):
    def _init_(self):
        super()._init_()
        self.Matrix1 = nn.Linear(2,8,bias=False)
        self.Matrix2 = nn.Linear(8,1,bias=False)
        
    def forward(self,x):
        x = self.Matrix1(x)
        x = self.Matrix2(x)
        return x.squeeze()
        

In [54]:
f = MyNeuralNet()

In [55]:
yhat = f(x)
yhat

AttributeError: 'MyNeuralNet' object has no attribute 'Matrix1'